version: "3.8"

services:

  mongo:
    image: bitnami/mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/bitnami/mongodb
  

volumes:
  mongo-data: