version: "3.8"

services:

  mongo:
    image: bitnami/mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongo-data:/bitnami/mongodb
volumes:
  mongo-data: